In [3]:
pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.2
[notice] To update, run: C:\Users\UseR\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [6]:
#creating an array
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [9]:
# creating zero dimension array
arrzero = np.array(11)
print(arrzero)

11


In [10]:
#checking dimension of the array
arr.ndim

1

In [11]:
arrzero.ndim

0

In [16]:
# creating t2-D array
arrtwo = np.array([[1,2,3,8,9],[4,5,6,7,8]])
print(arrtwo)
arrtwo.ndim

[[1 2 3 8 9]
 [4 5 6 7 8]]


2

In [18]:
# number of elements
arrtwo.size

10

In [19]:
#total memory size of array
arrtwo.nbytes

80

In [20]:
arrzero.nbytes

8

In [22]:
#single element size
arrtwo.itemsize

8

In [23]:
#datatype of array
arrtwo.dtype

dtype('int64')

In [24]:
print(arrtwo)

[[1 2 3 8 9]
 [4 5 6 7 8]]


In [25]:
#for a specific element
arrtwo[0,2]

np.int64(3)

In [26]:
#filtering specific row from the array
arrtwo[0,:]

array([1, 2, 3, 8, 9])

In [27]:
arrtwo[1,:]

array([4, 5, 6, 7, 8])

In [28]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11])
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [35]:
# start index is inclusive, and ending index is exclusive
arr3[1:5]

array([2, 3, 4, 5])

In [33]:
print(arr3[4:])

[ 5  6  7  8  9 10 11]


In [34]:
print(arr3[:5])

[1 2 3 4 5]


In [36]:
print(arrtwo)

[[1 2 3 8 9]
 [4 5 6 7 8]]


In [37]:
print(arrtwo[1,1:4])

[5 6 7]


In [38]:
#copying of an array
arr4 = arrtwo.copy()
print(arr4)

[[1 2 3 8 9]
 [4 5 6 7 8]]


In [40]:
# Zero matrix
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
# All 1 matrix
np.ones((5,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [47]:
# other matrix
np.full((4,4),28)

array([[28, 28, 28, 28],
       [28, 28, 28, 28],
       [28, 28, 28, 28],
       [28, 28, 28, 28]])

In [48]:
#importing random
from numpy import random

In [49]:
x = random.randint(100)
print(x)

20


In [54]:
np.random.rand(4,5)

array([[0.78847864, 0.41985927, 0.97227915, 0.23780408, 0.02819423],
       [0.10849133, 0.8693498 , 0.32458603, 0.6674564 , 0.17420419],
       [0.01524053, 0.28778533, 0.45414164, 0.21110492, 0.86179768],
       [0.86496943, 0.05029313, 0.65930719, 0.77535817, 0.19228107]])

In [56]:
# identity matrix
np.identity(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [60]:
# Mathematical operations on aaray
arrm = np.array([10,20,20,30])
print(arrm)

[10 20 20 30]


In [64]:
# + operation
arrm = arrm + 15
arrm

array([25, 35, 35, 45])

In [65]:
arrm

array([25, 35, 35, 45])

In [67]:
arrm = arrm-20
print(arrm)

[ 5 15 15 25]


In [69]:
arrz = arrm + 100
print(arrz)

[105 115 115 125]


In [71]:
# multiplication
print(arrm)
arrm*10

[ 5 15 15 25]


array([ 50, 150, 150, 250])

In [73]:
# Division
arrm/2

array([ 2.5,  7.5,  7.5, 12.5])

In [74]:
a1 = np.array([1,3,3,4,5,6])
a2 = np.array([2,6,6,5,4,5])
print(a1 + a2)

[ 3  9  9  9  9 11]


In [75]:
#cos function in array
np.cos(a1)

array([ 0.54030231, -0.9899925 , -0.9899925 , -0.65364362,  0.28366219,
        0.96017029])

In [76]:
#minimum value of array and maximum value of array
print(arrtwo)

[[1 2 3 8 9]
 [4 5 6 7 8]]


In [79]:
np.min(arrtwo)

np.int64(2)

In [80]:
np.max(arrtwo)

np.int64(9)

In [81]:
np.sum(arrtwo)

np.int64(53)

In [83]:
# iterating in 1-D array
for x in a1:
    print(x)

1
3
3
4
5
6


In [84]:
# iterating in 2-D array
for z in arrtwo:
    print(z)

[1 2 3 8 9]
[4 5 6 7 8]


In [85]:
for n in arrtwo:
    for b in n:
        print(b)

1
2
3
8
9
4
5
6
7
8
